version: '3.8'

services:
  pictures2obsidian:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pictures2obsidian-app
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - obsidian-vault:/app/api_vault
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/docs"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  obsidian-vault:
    driver: local
    driver_opts:
      type: none
      o: bind
      # Update this path to your actual Obsidian vault path
      # Windows example: device: "C:\\Users\\isaac\\Documents\\Obsidian Vault\\OCR"
      # Linux/macOS example: device: "/path/to/your/obsidian/vault"
      device: "${OBSIDIAN_VAULT_PATH:-/tmp/obsidian-vault}"